"""empty message

Revision ID: ef9597395a09
Revises: 3bcc68aa03a8
Create Date: 2025-02-01 22:27:38.050003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9597395a09'
down_revision: Union[str, None] = '3bcc68aa03a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
